### ISSUE TITLE
Install issues on platform 2.0

### ISSUE THREAD

**Issue by rauanmaemirov** [stevebauman/platform-logs#1]
Extension (v1.0.*) doesn't seem to work on platform 2.0, i've got exceptions right after composer update.
It somehow could not find database/migrations and seeds (which are don't exist in extension path).

**Comment by stevebauman** [comment]
Yea sorry about that, I haven't tested installing this yet on a new platform install. I'll be doing some testing this week getting it composer ready. Have just been working on other packages as well.

**Comment by rauanmaemirov** [comment]
Thanks. I was looking hard for this very package.

**Comment by stevebauman** [comment]
No problem, should hopefully be ready for tomorrow. I'll update here.

**Comment by stevebauman** [comment]
Ok it's good to go now. Installed and tested in a fresh platform 2.0 install. Run `composer update` and you should be all set.

**Comment by rauanmaemirov** [comment]
Apparently, v1.0.* requires foundation 2.0.* (platform 3.0) starting from v1.0.2, and it doesn't respect semver convention. :) I couldn't install it.

**Comment by stevebauman** [comment]
That's correct. Apologies, their versioning threw me off, I forgot foundation 2.0 is for the Laravel 5 variant of platform. 

I always try to respect semver, however in this case of missing dependencies in the `composer.json`, I felt a need to update it as soon as possible with the `v1.0` tag allowing an easy update. I haven't tried this package with the Laravel 4 variant of platform (v2) since my own development needs have fallen into the Laravel 5 variant for the time being.

There may be some difficulty providing an extension that works with not only Laravel 4 and 5, but as well as platform version 2 and 3. At the moment this package isn't my main focus for the time being, however feel free to provide pull requests if you attain complete compatibility.

If I update this package myself with laravel 4 and platform v2 compatibility, I'll update here.

**Comment by rauanmaemirov** [comment]
I understand. I guess I'll get my hands on it after upgrade.

2015-04-07 3:00 GMT+06:00 Steve Bauman <notifications@github.com>:

**Comment by stevebauman** [comment]
Ok, nevermind about that compatibility stuff I mentioned, updated for use on platform v2 and v3. Use `v1.1.*`. Just tested with a fresh install on platform v2.

**Comment by stevebauman** [comment]
I'll re-open this for the time being, definitely follow up if possible and let me know if it's working correctly for you!

**Comment by rauanmaemirov** [comment]
Hey Steve, everything works fine on platform 2. :+1:

**Comment by stevebauman** [comment]
Awesome, thanks for following up.
